In [1]:
import pandas as pd

In [2]:
gnpn=pd.read_csv(r"C:\Vaishnavi\Nasa\gagnepian_2006_catalog.csv")

In [3]:
gnpn.head()

,Type,Lat,Long,Depth,Date,YN_Lat,YN_Lon,YN_Depth,Phi,Delta-a,Delta-b,Depth_err
0,12 LM,-3.94,-21.20,0,6911202217,-3.94,-21.20,0,0,0.0,0.0,0
1,13 S-IVB,-2.75,-27.86,0,7004150209,-2.75,-27.86,0,0,0.0,0.0,0
2,14 S-IVB,-8.09,-26.02,0,7102040740,-8.09,-26.02,0,0,0.0,0.0,0
3,14 LM,-3.42,-19.67,0,7102070045,-3.42,-19.67,0,0,0.0,0.0,0
4,15 S-IVB,-1.51,-11.81,0,7107292058,1.51,-11.81,0,0,0.0,0.0,0

In [4]:
lognonne=pd.read_csv(r"C:\Vaishnavi\Nasa\lognonne_2003_catalog.csv")

In [5]:
lognonne

,Type,Lat,Long,Depth,Phi,Delta-a,Delta-b,Depth_err,Date,Seconds,...,16P,16P_EC,12S,12S_EC,14S,14S_EC,15S,15S_EC,16S,16S_EC
0,12 LM,-3.94,-21.20,0.0,0,0.0,0.0,0,6911202217,17.70,...,NaN,NaN,56.29,2.0,NaN,NaN,NaN,NaN,NaN,NaN
1,13 S-IVB,-2.75,-27.86,0.0,0,0.0,0.0,0,7004150209,41.00,...,NaN,NaN,89.04,2.0,NaN,NaN,NaN,NaN,NaN,NaN
2,14 S-IVB,-8.09,-26.02,0.0,0,0.0,0.0,0,7102040740,55.40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,14 LM,-3.42,-19.67,0.0,0,0.0,0.0,0,7102070045,25.70,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15 S-IVB,-1.51,-11.81,0.0,0,0.0,0.0,0,7107292058,42.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,15 LM,26.36,0.25,0.0,0,0.0,0.0,0,7108030303,37.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16 S-IVB,1.30,-23.80,0.0,0,0.0,0.0,0,7204192102,4.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,17 S-IVB,-4.21,-12.31,0.0,0,0.0,0.0,0,7212102032,42.30,...,164.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,M,74.10,2.60,0.0,16,2.7,1.1,0,7201040631,19.72,...,NaN,NaN,542.00,2.0,NaN,NaN,350.0,1.0,NaN,NaN
9,M,1.50,-17.10,0.0,-52,0.3,0.2,0,7205130845,39.49,...,181.0,0.0,NaN,NaN,97.5,2.0,NaN,NaN,NaN,NaN
10,M,32.80,137.60,0.0,-47,1.3,1.1,0,7207172150,57.90,...,445.8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,M,24.00,10.10,0.0,-7,0.7,0.3,0,7207311808,15.72,...,NaN,NaN,285.00,2.0,NaN,NaN,82.0,1.0,NaN,NaN
12,M,15.80,22.90,0.0,20,2.9,1.6,0,7208292258,33.57,...,145.0,2.0,NaN,NaN,344.0,2.0,190.0,2.0,NaN,NaN
13,M,28.70,41.10,0.0,39,4.1,2.4,0,7309262046,16.32,...,192.0,2.0,NaN,NaN,NaN,NaN,255.0,2.0,NaN,NaN
14,M,-24.80,-25.10,0.0,59,5.2,1.8,0,7312241003,19.35,...,190.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,M,7.40,-33.60,0.0,-5,2.2,0.9,0,7404191830,3.27,...,209.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,M,20.30,6.50,0.0,9,0.8,0.6,0,7407171205,2.89,...,132.1,1.0,NaN,NaN,NaN,NaN,69.0,2.0,NaN,NaN
17,M,-7.30,19.90,0.0,52,1.0,0.7,0,7411211315,40.79,...,70.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,M,1.60,-8.20,0.0,-85,1.3,0.5,0,7412150907,15.17,...,128.1,1.0,NaN,NaN,109.3,2.0,208.2,2.0,NaN,NaN
19,M,-52.40,4.20,0.0,-77,4.0,2.3,0,7503052149,22.30,...,209.7,2.0,398.00,2.0,NaN,NaN,NaN,NaN,330.0,2.0
20,M,2.00,43.20,0.0,-11,4.5,0.5,0,7504121812,38.22,...,162.1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,M,-36.40,-121.30,0.0,-47,3.3,1.1,0,7505040959,28.99,...,413.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,M,-39.40,62.80,0.0,55,2.7,2.0,0,7601130711,22.80,...,236.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,357.9,2.0
23,M,-16.80,-10.00,0.0,67,2.0,0.6,0,7605280601,56.38,...,169.0,1.0,216.00,2.0,169.0,2.0,373.0,2.0,NaN,NaN
24,M,23.80,-73.90,0.0,37,1.8,0.8,0,761142313,6.67,...,337.7,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,M,-20.50,-63.80,0.0,23,1.8,0.8,0,7704712332,6.03,...,298.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,M,-13.50,-75.30,0.0,-84,7.7,3.1,0,7706282222,31.17,...,358.5,2.0,390.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN
27,SH,12.80,51.00,NaN,-20,2.9,109.0,109,7209171435,3.00,...,170.0,2.0,NaN,NaN,460.0,2.0,322.0,2.0,285.0,2.0
28,SH,48.00,38.20,10.0,58,3.2,110.0,110,7212062308,33.40,...,280.0,2.0,NaN,NaN,507.0,2.0,278.0,2.0,430.0,2.0
29,SH,21.90,82.60,2.0,-10,2.4,63.0,63,7407110046,18.26,...,297.7,0.0,655.90,2.0,NaN,NaN,485.1,2.0,NaN,NaN
30,SH,26.10,-92.70,0.0,42,2.4,38.0,38,7501030141,58.36,...,434.9,1.0,543.00,2.0,581.0,2.0,608.0,2.0,730.0,2.0
31,SH,64.10,59.90,0.0,59,1.8,14.0,14,7501120313,51.74,...,350.0,2.0,612.90,2.0,NaN,NaN,400.0,0.0,567.6,0.0
32,SH,-17.00,-26.10,21.0,44,3.0,112.0,112,7502132203,50.78,...,210.0,2.0,154.40,2.0,167.8,2.0,NaN,NaN,321.7,2.0
33,SH,44.10,34.00,125.0,76,3.2,179.0,179,7601041118,54.92,...,262.0,1.0,NaN,NaN,474.0,2.0,259.0,2.0,412.0,2.0
34,SH,52.50,-25.80,185.0,-24,1.2,51.0,51,7603061012,22.08,...,282.6,1.0,381.30,1.0,387.7,1.0,251.2,2.0,466.1,2.0
35,A01,-17.40,-38.40,917.0,-25,1.1,0.6,11,7309300410,58.84,...,239.7,1.0,290.50,1.0,300.6,2.0,396.8,0.0,377.8,2.0
36,A06,49.70,54.70,860.0,74,1.0,0.7,11,7607021052,25.31,...,235.2,0.0,444.70,0.0,433.3,1.0,316.9,1.0,377.9,1.0
37,A07,24.00,53.70,900.0,-75,0.8,0.7,12,7607020311,24.18,...,198.8,1.0,426.10,1.0,408.2,0.0,314.5,1.0,332.4,1.0
38,A08,-28.00,-28.10,940.0,51,2.0,1.2,21,7705161052,29.35,...,189.9,1.0,270.50,1.0,276.3,0.0,NaN,NaN,328.9,1.0
39,A09,-37.80,-30.80,975.0,14,4.0,2.6,43,7704161958,4.27,...,NaN,0.0,277.10,0.0,277.7,1.0,377.1,2.0,320.3,2.0
40,A11,9.30,17.50,1200.0,-42,0.8,0.7,12,7706180501,16.06,...,NaN,0.0,329.30,0.0,319.8,0.0,299.4,0.0,296.4,0.0
41,A14,-28.70,-33.90,880.0,50,1.7,1.3,22,7305281853,12.96,...,191.0,1.0,254.80,1.0,260.5,1.0,370.1,1.0,319.7,1.0
42,A16,6.80,5.10,1105.0,9,1.2,0.7,18,721081524,35.48,...,185.4,1.0,315.20,1.0,305.5,1.0,298.6,0.0,298.3,1.0
43,A17,23.10,-18.00,861.0,-47,2.6,0.4,15,7211070852,7.94,...,178.0,1.0,246.20,1.0,243.9,1.0,228.9,0.0,NaN,NaN
44,A18,18.60,34.70,882.0,-67,1.8,0.9,24,7301052250,30.86,...,188.5,1.0,373.20,1.0,357.5,0.0,276.5,1.0,279.6,2.0
45,A20,21.70,-41.00,1055.0,-1,2.4,0.8,13,7205151718,7.15,...,204.5,0.0,279.20,0.0,284.1,1.0,NaN,NaN,357.3,1.0
46,A24,-36.80,-38.90,980.0,57,2.1,1.7,32,7706121817,38.54,...,NaN,2.0,315.80,2.0,319.7,0.0,417.8,2.0,368.0,1.0
47,A25,34.40,59.30,898.0,87,2.0,1.7,26,7706092015,7.55,...,200.7,NaN,NaN,NaN,409.3,1.0,312.7,1.0,345.6,2.0
48,A27,22.50,18.50,1059.0,-24,1.9,1.4,14,7705160001,51.54,...,205.9,2.0,366.00,2.0,352.3,1.0,299.9,0.0,338.9,2.0
49,A30,11.80,-34.30,921.0,-37,1.5,1.0,23,7205170042,45.93,...,NaN,1.0,273.30,1.0,283.4,1.0,321.4,1.0,365.2,1.0
50,A33,6.90,117.80,887.0,-9,1.5,1.3,30,7210111935,46.79,...,311.8,NaN,NaN,NaN,NaN,NaN,528.1,1.0,511.5,1.0
51,A34,7.00,-9.30,932.0,-32,1.2,0.6,26,7206141834,27.24,...,NaN,1.0,249.80,1.0,256.5,1.0,265.2,0.0,279.3,1.0
52,A40,-1.60,-10.90,886.0,-80,1.2,0.7,23,7306272348,35.37,...,173.1,0.0,247.90,0.0,242.6,1.0,286.7,1.0,277.8,1.0
53,A41,13.90,-26.80,953.0,-28,5.6,2.2,84,7206081616,24.70,...,NaN,2.0,247.30,2.0,270.1,2.0,284.1,1.0,325.6,2.0
54,A42,22.70,-53.50,1004.0,-53,1.8,1.4,24,7305030152,35.84,...,245.6,1.0,318.90,1.0,331.9,1.0,352.5,1.0,418.0,1.0
55,A44,51.90,57.10,956.0,-74,5.8,1.9,20,7405190309,4.66,...,NaN,2.0,434.90,2.0,411.4,0.0,307.4,1.0,376.2,2.0
56,A50,9.40,-51.60,835.0,-13,2.4,1.5,30,7304300105,26.01,...,NaN,2.0,292.00,2.0,285.0,1.0,348.1,1.0,397.8,1.0
57,A51,8.80,15.70,888.0,-28,1.1,0.5,22,7402180835,27.40,...,NaN,2.0,320.70,2.0,291.1,0.0,254.1,0.0,248.8,1.0
58,A97,-3.40,18.70,1000.0,-3,2.8,2.3,25,7705190608,21.53,...,156.0,2.0,310.30,2.0,295.2,2.0,301.1,2.0,251.8,1.0

In [6]:
nak79=pd.read_csv(r"C:\Vaishnavi\Nasa\nakamura_1979_sm_locations.csv")

In [7]:
nak79

    Year  Day   H   M   S   Lat   Long  Magnitude
0   1971  107   7   0  55  48.0   35.0        2.8
1   1971  140  17  25  10  42.0  -24.0        2.0
2   1971  192  13  24  45  43.0  -47.0        1.9
3   1972    2  22  29  40  54.0  101.0        1.9
4   1972  261  14  35  55  12.0   46.0        1.0
5   1972  341  23   8  20  51.0   45.0        1.4
6   1972  344   3  50  15 -20.0  -80.0        1.2
7   1973   39  22  52  10  33.0   35.0        0.8
8   1973   72   7  56  30 -84.0 -134.0        3.2
9   1973  171  20  22   0  -1.0  -71.0        2.2
10  1973  274   3  58   0 -37.0  -29.0        1.1
11  1974   54  21  16  50  36.0  -16.0        0.7
12  1974   86   9  11   0 -48.0 -106.0        1.6
13  1974  109  13  35  15 -37.0   42.0        0.9
14  1974  149  20  42  15   NaN    NaN        0.6
15  1974  192   0  46  30  21.0   88.0        2.7
16  1975    3   1  42   0  29.0  -98.0        3.2
17  1975   12   3  14  10  75.0   40.0        1.7
18  1975   13   0  26  20  -2.0  -51.0        1.1
19  1975   44  22   3  50 -19.0  -26.0        1.4
20  1975  127   6  37   5 -49.0  -45.0        1.3
21  1975  147  23  29   0   3.0  -58.0        1.4
22  1975  314   7  52  55  -8.0   64.0        1.8
23  1976    4  11  18  55  50.0   30.0        1.8
24  1976   12   8  18   5  38.0   44.0        1.1
25  1976   66  10  12  40  50.0  -20.0        2.3
26  1976   68  14  42  10 -19.0  -12.0        1.8
27  1976  137  12  32  40  77.0  -10.0        1.5

In [8]:
nak83_AI_arr=pd.read_csv(r"C:\Vaishnavi\Nasa\nakamura_1983_ai_arrivals.csv")

In [9]:
nak83_AI_arr

,AI,12P,14P,15P,16P,17P,12D,14D,15D,16D,17D,12T,14T,15T,16T,17T
0,12 LM,NaN,NaN,NaN,NaN,NaN,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13 S-IVB,10:09.6,NaN,NaN,NaN,NaN,135,NaN,NaN,NaN,NaN,28.6,NaN,NaN,NaN,NaN
2,14 S-IVB,41:31.1,NaN,NaN,NaN,NaN,172,NaN,NaN,NaN,NaN,35.7,NaN,NaN,NaN,NaN
3,14 LM,45:52.0,45:44.5,NaN,NaN,NaN,114,67.0,NaN,NaN,NaN,25.0,17.8,NaN,NaN,NaN
4,15 S-IVB,59:37.9,59:19.5,NaN,NaN,NaN,355,184.0,NaN,NaN,NaN,55.0,36.6,NaN,NaN,NaN
5,15 LM,NaN,NaN,03:59.0,NaN,NaN,1130,1048.0,93.0,NaN,NaN,NaN,NaN,22.0,NaN,NaN
6,17 S-IVB,33:38.3,33:14.3,35:13.0,34:45.4,NaN,338,157.0,1032.0,850.0,NaN,56.0,32.0,151.0,123.1,NaN
7,17 LM,NaN,NaN,NaN,NaN,50:26.6,1750,1599.0,770.0,986.0,9.0,NaN,NaN,NaN,NaN,5.8

In [10]:
nak83_AI_loc=pd.read_csv(r"C:\Vaishnavi\Nasa\nakamura_1983_ai_locations.csv")

In [11]:
nak83_AI_loc

         AI    Lat   Long   Y   JD  Hour  Min   Sec
0     12 LM  -3.94 -21.20  69  324    22   17  17.7
1  13 S-IVB  -2.75 -27.86  70  105     1    9  41.0
2  14 S-IVB  -8.09 -26.02  71   35     7   40  55.4
3     14 LM  -3.42 -19.67  71   38     0   45  26.7
4  15 S-IVB  -1.51 -11.81  71  210    20   58  42.9
5     15 LM  26.36   0.25  71  215     3    3  37.0
6  17 S-IVB  -4.21 -12.31  72  345    20   32  42.3
7     17 LM  19.99  30.51  72  350     6   50  20.8

In [12]:
nak83_M_arr=pd.read_csv(r"C:\Vaishnavi\Nasa\nakamura_1983_m_arrivals.csv")

In [23]:
nak83_M_arr.fillna(0)

,Year,Day,Hour,Station,P_YN,P_NG,P_JK,P_PH,P_Mean,S_YN,S_NG,S_JK,S_PH,S_Mean
0,1971.0,143.0,2220.0,12,19.5,0.0,0.0,19.5,19.5,0.0,0.0,0.0,50.0,50.0
1,0.0,0.0,0.0,14,6.6,0.0,0.0,6.5,6.6,0.0,0.0,0.0,28.0,28.0
2,1971.0,163.0,1051.0,12,51.9,0.0,0.0,52.0,52.0,0.0,0.0,0.0,164.0,164.0
3,0.0,0.0,0.0,14,59.0,0.0,0.0,58.5,58.8,0.0,0.0,0.0,176.0,176.0
4,1971.0,293.0,1808.0,12,31.9,0.0,0.0,35.5,33.7,0.0,0.0,0.0,143.0,143.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,0.0,0.0,0.0,16,158.2,0.0,0.0,158.5,158.4,0.0,0.0,0.0,0.0,0.0
61,1977.0,107.0,2335.0,12,6.4,6.9,6.6,6.0,6.5,0.0,0.0,178.1,141.0,159.6
62,0.0,0.0,0.0,14,18.8,18.3,19.5,19.5,19.0,170.0,0.0,198.6,160.0,176.2
63,0.0,0.0,0.0,15,129.0,127.9,128.3,130.0,128.8,0.0,0.0,0.0,361.0,361.0
64,0.0,0.0,0.0,16,119.3,126.5,119.6,119.0,121.1,0.0,0.0,0.0,0.0,0.0

In [14]:
nak83_SM_arr=pd.read_csv(r"C:\Vaishnavi\Nasa\nakamura_1983_sm_arrivals.csv")

In [15]:
nak83_SM_arr

,Year,Day,Hour,Station,P_YN,P_NG,P_JK,P_PH,P_Mean,S_YN,S_NG,S_JK,S_PH,S_Mean
0,1971.0,107.0,705.0,12,9.6,NaN,NaN,10.0,9.8,212.0,NaN,NaN,210.0,211.0
1,NaN,NaN,NaN,14,1.9,NaN,NaN,1.5,1.7,182.0,NaN,NaN,192.0,187.0
2,1971.0,140.0,1728.0,12,NaN,NaN,NaN,NaN,NaN,183.0,NaN,NaN,183.5,183.3
3,NaN,NaN,NaN,14,60.2,NaN,NaN,60.0,60.1,184.0,NaN,NaN,186.0,185.0
4,1971.0,192.0,1327.0,12,58.2,NaN,NaN,54.3,56.2,200.0,NaN,NaN,200.0,200.0
5,NaN,NaN,NaN,14,70.4,NaN,NaN,72.5,71.5,225.0,NaN,NaN,233.0,229.0
6,1972.0,2.0,2233.0,14,170.0,NaN,NaN,NaN,170.0,485.0,NaN,NaN,NaN,485.0
7,NaN,NaN,NaN,15,52.0,NaN,NaN,NaN,52.0,250.0,NaN,NaN,NaN,250.0
8,1973.0,72.0,801.0,12,34.2,34.1,34.2,34.0,34.1,267.0,272.0,267.0,NaN,268.7
9,NaN,NaN,NaN,14,35.5,35.9,35.5,35.0,35.5,280.0,NaN,272.5,NaN,276.3
10,NaN,NaN,NaN,15,100.0,99.7,100.0,109.0,102.2,465.0,NaN,398.5,NaN,431.8
11,NaN,NaN,NaN,16,27.2,27.8,27.9,27.5,27.6,270.0,259.4,258.6,266.0,263.5
12,1973.0,171.0,2024.0,12,56.1,55.0,56.0,NaN,55.7,180.0,185.3,187.5,182.0,183.7
13,NaN,NaN,NaN,14,66.6,66.5,67.0,54.0,63.5,219.0,NaN,207.5,215.0,213.8
14,NaN,NaN,NaN,15,147.5,145.7,147.5,156.0,149.2,360.0,NaN,346.0,NaN,353.0
15,NaN,NaN,NaN,16,190.7,198.5,191.0,NaN,193.4,430.0,412.5,422.5,NaN,421.7
16,1974.0,192.0,50.0,12,138.7,138.5,138.7,NaN,138.6,459.0,NaN,417.0,NaN,438.0
17,NaN,NaN,NaN,14,128.6,125.3,128.6,128.0,127.6,439.0,NaN,407.0,NaN,423.0
18,NaN,NaN,NaN,15,57.5,56.5,57.5,57.0,57.1,255.0,NaN,263.0,242.0,253.3
19,NaN,NaN,NaN,16,59.8,50.3,59.8,55.5,56.3,270.0,NaN,270.0,240.0,260.0
20,1975.0,3.0,146.0,12,33.5,33.6,33.5,34.0,33.7,NaN,269.0,255.0,NaN,262.0
21,NaN,NaN,NaN,14,51.2,51.3,51.2,51.0,51.2,280.0,NaN,285.0,275.0,280.0
22,NaN,NaN,NaN,15,61.1,60.5,61.1,62.5,61.3,300.0,NaN,300.0,NaN,300.0
23,NaN,NaN,NaN,16,135.0,127.5,135.0,133.0,132.6,510.0,453.0,510.0,NaN,491.0
24,1975.0,12.0,317.0,14,137.7,NaN,137.5,140.0,138.4,368.0,NaN,356.0,NaN,362.0
25,NaN,NaN,NaN,15,20.0,NaN,30.0,24.0,24.7,162.0,NaN,162.0,161.0,161.7
26,NaN,NaN,NaN,16,124.8,NaN,125.0,NaN,124.9,331.0,NaN,331.0,331.0,331.0
27,1975.0,44.0,2204.0,14,58.3,58.2,58.0,NaN,58.2,108.0,107.8,108.0,NaN,107.9
28,NaN,NaN,NaN,15,190.4,189.5,190.4,NaN,190.1,330.0,325.0,329.5,NaN,328.2
29,NaN,NaN,NaN,16,140.9,149.6,145.5,NaN,145.3,265.0,257.0,265.0,NaN,262.3
30,1975.0,314.0,755.0,14,160.0,NaN,NaN,NaN,160.0,370.0,NaN,NaN,NaN,370.0
31,NaN,NaN,NaN,15,120.0,NaN,NaN,NaN,120.0,300.0,NaN,NaN,NaN,300.0
32,NaN,NaN,NaN,16,50.0,NaN,NaN,NaN,50.0,180.0,NaN,NaN,NaN,180.0
33,1976.0,4.0,1120.0,14,NaN,NaN,NaN,NaN,NaN,353.0,353.8,NaN,NaN,353.4
34,NaN,NaN,NaN,15,53.1,55.1,NaN,NaN,54.1,141.0,142.0,NaN,NaN,141.5
35,NaN,NaN,NaN,16,148.0,147.7,NaN,NaN,147.9,310.0,312.0,NaN,NaN,311.0
36,1976.0,66.0,1014.0,12,118.0,110.8,110.8,NaN,113.2,263.0,262.0,263.0,262.5,262.6
37,NaN,NaN,NaN,14,113.6,113.3,112.0,113.5,113.1,268.0,268.7,268.0,267.5,268.1
38,NaN,NaN,NaN,15,35.1,39.2,38.0,38.5,37.7,124.0,135.8,130.0,132.5,130.6
39,NaN,NaN,NaN,16,161.5,NaN,161.0,NaN,161.3,347.0,346.0,355.0,NaN,349.3
40,1976.0,68.0,1443.0,12,NaN,NaN,NaN,NaN,NaN,NaN,98.8,NaN,NaN,98.8
41,NaN,NaN,NaN,14,21.8,24.2,22.0,20.0,22.0,69.0,70.3,69.0,69.0,69.3
42,NaN,NaN,NaN,15,138.3,141.5,141.0,139.5,140.1,272.0,272.1,273.0,271.0,272.0
43,NaN,NaN,NaN,16,65.0,74.9,65.0,66.0,67.7,149.0,NaN,149.0,150.0,149.3

In [16]:
nak05_DM_arr=pd.read_csv(r"C:\Vaishnavi\Nasa\nakamura_2005_dm_arrivals.csv")

In [17]:
nak05_DM_arr

       A  12P  14P  15P  16P  12S  14S  15S  16S
0      1  138  140  197  184  230  233  341  323
1      2                      220  228
2      3       122            227  230  311  330
3      4                      205  203       270
4      5       141            232  242       351
..   ...  ...  ...  ...  ...  ...  ...  ...  ...
161  286            118                 248  321
162  287                           330  246  272
163  288                           185       280
164  289                           277  239
165  290                           263  240  250

[166 rows x 9 columns]

In [18]:
nak05_DM_loc=pd.read_csv(r"C:\Vaishnavi\Nasa\nakamura_2005_dm_locations.csv")

In [19]:
nak05_DM_loc

       A Side   Lat  Lat_err   Long  Long_err  Depth  Depth_err Assumed
0      1    N -15.7      2.4  -36.6       4.6    867         29       N
1      3    N  -2.9      1.7  -50.3       6.3    946         22       N
2      5    N   1.1     94.2  -44.7      16.4    933        109       Y
3      6    N  43.5      2.9   55.5       9.5    844         33       N
4      7    N  25.0      1.7   53.2       8.0    893         27       N
..   ...  ...   ...      ...    ...       ...    ...        ...     ...
101  283    N   7.1      1.2   22.5       4.7    984         76       N
102  285    F  42.9      3.7  110.9      14.2    933        109       Y
103  286    N  54.2      6.5   56.5      14.0    933        109       Y
104  287    N  24.8      5.7   35.7      13.5    933        109       Y
105  290    N  10.6      1.6    6.4       1.9    933        109       Y

[106 rows x 9 columns]

In [20]:
weber=pd.read_csv(r"C:\Vaishnavi\Nasa\weber_2011_dmq_s_picks.csv")

In [21]:
weber

      A#    S12    S14    S15    S16
0     A1  226.0  235.7  338.9  314.6
1     A3  255.4    NaN    NaN    NaN
2     A5  235.1    NaN    NaN    NaN
3     A6  418.4    NaN  298.0  371.3
4     A7  410.6  409.3  366.8  360.9
5     A8    NaN    NaN    NaN  328.8
6     A9  244.1    NaN    NaN    NaN
7    A10    NaN  289.0    NaN  297.2
8    A13  260.5    NaN    NaN    NaN
9    A14  268.7    NaN    NaN    NaN
10   A15  237.3    NaN    NaN    NaN
11   A16  271.4    NaN  253.2    NaN
12   A17  238.5    NaN  224.4  297.3
13   A18  357.8  337.1  270.0  281.5
14   A20  258.0    NaN    NaN  328.6
15   A21  278.4    NaN    NaN    NaN
16   A22  385.8    NaN  244.1  281.2
17   A25  440.4  417.5  335.4  362.1
18   A26  278.2  291.9    NaN    NaN
19   A27    NaN    NaN  275.2    NaN
20   A30  225.3    NaN    NaN    NaN
21   A34  251.2    NaN    NaN    NaN
22   A35    NaN    NaN    NaN  249.0
23   A40  229.7    NaN    NaN  247.4
24   A41  226.3    NaN    NaN    NaN
25   A42    NaN    NaN  309.8    NaN
26   A44  429.0    NaN    NaN    NaN
27   A51    NaN    NaN    NaN  290.4
28   A70    NaN    NaN    NaN  356.8
29   A82    NaN    NaN    NaN  280.2
30   A86    NaN    NaN    NaN  346.5
31   A97    NaN    NaN    NaN  234.8
32   A99    NaN    NaN    NaN  241.2
33  A201  289.7    NaN    NaN    NaN
34  A203    NaN    NaN    NaN  323.0
35  A224  328.9    NaN    NaN  325.0
36  A241    NaN    NaN    NaN  383.5
37  A257    NaN    NaN  258.5    NaN